crystals:
  bgo:
    t1: 50
    a1: 0.044
    t2: 320
    a2: 0.093
  bso:
    t1: 22
    a1: 0.054
    t2: 98
    a2: 0.087
  pwo:
    t1: 7.5
    a1: 1.0
    t2: 0.0
    a2: 0.0

sipm:

  6x6:
    gain:
      "28db": 3.621
      "18db": 1.163
    dcr: 0
    times:
      tf: 150
      tr: 1
      fc: 4.3e-5

  3x3:
    gain:
      "28db": 1.236
      "18db": 0.401
      filter: 0.0425
    dcr: 0
    times:
      tf: 48
      tr: 1
      fc: 8e-6
